name: Build & Deploy NuGet

# doc: https://docs.github.com/en/actions
# variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17

on:
  workflow_run:
    workflows: ["Prepare"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
  
jobs: 
  build-nuget:
    uses: weknow-network/weknow-workflows/.github/workflows/dotnet-build-deploy-public-nuget.yml@release/2023-02-15
    secrets:
      NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}
    with:
      build-config: Release
      dotnet-version: 7.0.x
      include-prerelease: false
      test-project: Tests/Weknow.Cypher.Builder.UnitTests


  #code-covarage:
  #  uses: b3b00/coverlet-action@1.1.9
  #  with:
  #    testProject: 'Tests/Weknow.Cypher.Builder.UnitTests/Weknow.Cypher.Builder.UnitTests.csproj'
  #    output: 'lcov.info'
  #    outputFormat: 'lcov'
  #    excludes: '[program]*,[test]test.*'
  #    threshold: 80
 